# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./*.h
SOURCES += ./*.cpp
FORMS += ./streetgenerator.ui 
RESOURCES += streetgenerator.qrc
